name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
        
    # Cache Go modules
    - name: Go Module Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Cache Fyne CLI
    - name: Fyne CLI Cache
      uses: actions/cache@v4
      with:
        path: ~/go/bin/fyne.exe
        key: ${{ runner.os }}-fyne-cli-${{ hashFiles('go.sum') }}
        
    - name: Set up MinGW
      continue-on-error: true
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        
    - name: Install Dependencies
      run: |
        if (!(Test-Path ~/go/bin/fyne.exe)) {
          go install fyne.io/fyne/v2/cmd/fyne@latest
        }
        
    # Cache build dependencies
    - name: Dependencies Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-build-
        
    - name: Build
      run: |
        $env:CC = "x86_64-w64-mingw32-gcc"
        go build -v -ldflags="-s -w -H=windowsgui" -trimpath -o orionchat.exe
        
    - name: Create ZIP
      run: |
        New-Item -ItemType Directory -Path release
        Copy-Item orionchat.exe release/
        New-Item -ItemType Directory -Path release/assets
        Copy-Item assets/* release/assets/ -Recurse
        Compress-Archive -Path release/* -DestinationPath "orionchat-${{ github.ref_name }}.zip"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: orionchat-${{ github.ref_name }}.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true