name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
        
    - name: Initialize Go Module
      run: |
        go mod init github.com/${{ github.repository }}
        go mod tidy
        
    - name: Build
      run: |
        go build -v -ldflags="-s -w" -trimpath -o app.exe
        
    - name: Create ZIP
      run: |
        # Create a temporary directory for the release
        New-Item -ItemType Directory -Path release
        # Copy executable to release dir
        Copy-Item app.exe release/
        # Create assets directory and copy files
        New-Item -ItemType Directory -Path release/assets
        Copy-Item assets/* release/assets/
        # Create the final ZIP
        Compress-Archive -Path release/* -DestinationPath "chat-tools-${{ github.ref_name }}.zip"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: chat-tools-${{ github.ref_name }}.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true